# This file contains version definitions
# Generated: 2026-09-19T17:02:22.946-04:00

resource.Account=org.hl7.fhir.model.core.Account
resource.ActivityDefinition=org.hl7.fhir.model.core.ActivityDefinition
resource.ActorDefinition=org.hl7.fhir.model.core.ActorDefinition
resource.AdministrableProductDefinition=org.hl7.fhir.model.core.AdministrableProductDefinition
resource.AdverseEvent=org.hl7.fhir.model.core.AdverseEvent
resource.AllergyIntolerance=org.hl7.fhir.model.core.AllergyIntolerance
resource.Appointment=org.hl7.fhir.model.core.Appointment
resource.AppointmentResponse=org.hl7.fhir.model.core.AppointmentResponse
resource.ArtifactAssessment=org.hl7.fhir.model.core.ArtifactAssessment
resource.AuditEvent=org.hl7.fhir.model.core.AuditEvent
resource.Basic=org.hl7.fhir.model.core.Basic
resource.Binary=org.hl7.fhir.model.core.Binary
resource.BiologicallyDerivedProduct=org.hl7.fhir.model.core.BiologicallyDerivedProduct
resource.BodyStructure=org.hl7.fhir.model.core.BodyStructure
resource.Bundle=org.hl7.fhir.model.core.Bundle
resource.CapabilityStatement=org.hl7.fhir.model.core.CapabilityStatement
resource.CarePlan=org.hl7.fhir.model.core.CarePlan
resource.CareTeam=org.hl7.fhir.model.core.CareTeam
resource.Claim=org.hl7.fhir.model.core.Claim
resource.ClaimResponse=org.hl7.fhir.model.core.ClaimResponse
resource.ClinicalUseDefinition=org.hl7.fhir.model.core.ClinicalUseDefinition
resource.CodeSystem=org.hl7.fhir.model.core.CodeSystem
resource.Communication=org.hl7.fhir.model.core.Communication
resource.CommunicationRequest=org.hl7.fhir.model.core.CommunicationRequest
resource.CompartmentDefinition=org.hl7.fhir.model.core.CompartmentDefinition
resource.Composition=org.hl7.fhir.model.core.Composition
resource.ConceptMap=org.hl7.fhir.model.core.ConceptMap
resource.Condition=org.hl7.fhir.model.core.Condition
resource.Consent=org.hl7.fhir.model.core.Consent
resource.Coverage=org.hl7.fhir.model.core.Coverage
resource.CoverageEligibilityRequest=org.hl7.fhir.model.core.CoverageEligibilityRequest
resource.CoverageEligibilityResponse=org.hl7.fhir.model.core.CoverageEligibilityResponse
resource.DetectedIssue=org.hl7.fhir.model.core.DetectedIssue
resource.Device=org.hl7.fhir.model.core.Device
resource.DeviceAlert=org.hl7.fhir.model.core.DeviceAlert
resource.DeviceAssociation=org.hl7.fhir.model.core.DeviceAssociation
resource.DeviceDefinition=org.hl7.fhir.model.core.DeviceDefinition
resource.DeviceMetric=org.hl7.fhir.model.core.DeviceMetric
resource.DeviceRequest=org.hl7.fhir.model.core.DeviceRequest
resource.DiagnosticReport=org.hl7.fhir.model.core.DiagnosticReport
resource.DocumentReference=org.hl7.fhir.model.core.DocumentReference
resource.Encounter=org.hl7.fhir.model.core.Encounter
resource.Endpoint=org.hl7.fhir.model.core.Endpoint
resource.EpisodeOfCare=org.hl7.fhir.model.core.EpisodeOfCare
resource.EventDefinition=org.hl7.fhir.model.core.EventDefinition
resource.Evidence=org.hl7.fhir.model.core.Evidence
resource.EvidenceVariable=org.hl7.fhir.model.core.EvidenceVariable
resource.ExampleScenario=org.hl7.fhir.model.core.ExampleScenario
resource.ExplanationOfBenefit=org.hl7.fhir.model.core.ExplanationOfBenefit
resource.FamilyMemberHistory=org.hl7.fhir.model.core.FamilyMemberHistory
resource.Flag=org.hl7.fhir.model.core.Flag
resource.Goal=org.hl7.fhir.model.core.Goal
resource.Group=org.hl7.fhir.model.core.Group
resource.GuidanceResponse=org.hl7.fhir.model.core.GuidanceResponse
resource.HealthcareService=org.hl7.fhir.model.core.HealthcareService
resource.ImagingSelection=org.hl7.fhir.model.core.ImagingSelection
resource.ImagingStudy=org.hl7.fhir.model.core.ImagingStudy
resource.Immunization=org.hl7.fhir.model.core.Immunization
resource.ImplementationGuide=org.hl7.fhir.model.core.ImplementationGuide
resource.Ingredient=org.hl7.fhir.model.core.Ingredient
resource.Library=org.hl7.fhir.model.core.Library
resource.List=org.hl7.fhir.model.core.ListResource
resource.Location=org.hl7.fhir.model.core.Location
resource.ManufacturedItemDefinition=org.hl7.fhir.model.core.ManufacturedItemDefinition
resource.Measure=org.hl7.fhir.model.core.Measure
resource.MeasureReport=org.hl7.fhir.model.core.MeasureReport
resource.Medication=org.hl7.fhir.model.core.Medication
resource.MedicationAdministration=org.hl7.fhir.model.core.MedicationAdministration
resource.MedicationDispense=org.hl7.fhir.model.core.MedicationDispense
resource.MedicationRequest=org.hl7.fhir.model.core.MedicationRequest
resource.MedicationStatement=org.hl7.fhir.model.core.MedicationStatement
resource.MedicinalProductDefinition=org.hl7.fhir.model.core.MedicinalProductDefinition
resource.MessageDefinition=org.hl7.fhir.model.core.MessageDefinition
resource.MessageHeader=org.hl7.fhir.model.core.MessageHeader
resource.NamingSystem=org.hl7.fhir.model.core.NamingSystem
resource.NutritionIntake=org.hl7.fhir.model.core.NutritionIntake
resource.NutritionOrder=org.hl7.fhir.model.core.NutritionOrder
resource.NutritionProduct=org.hl7.fhir.model.core.NutritionProduct
resource.Observation=org.hl7.fhir.model.core.Observation
resource.ObservationDefinition=org.hl7.fhir.model.core.ObservationDefinition
resource.OperationDefinition=org.hl7.fhir.model.core.OperationDefinition
resource.OperationOutcome=org.hl7.fhir.model.core.OperationOutcome
resource.Organization=org.hl7.fhir.model.core.Organization
resource.OrganizationAffiliation=org.hl7.fhir.model.core.OrganizationAffiliation
resource.PackagedProductDefinition=org.hl7.fhir.model.core.PackagedProductDefinition
resource.Parameters=org.hl7.fhir.model.core.Parameters
resource.Patient=org.hl7.fhir.model.core.Patient
resource.PaymentNotice=org.hl7.fhir.model.core.PaymentNotice
resource.PaymentReconciliation=org.hl7.fhir.model.core.PaymentReconciliation
resource.Person=org.hl7.fhir.model.core.Person
resource.PlanDefinition=org.hl7.fhir.model.core.PlanDefinition
resource.Practitioner=org.hl7.fhir.model.core.Practitioner
resource.PractitionerRole=org.hl7.fhir.model.core.PractitionerRole
resource.Procedure=org.hl7.fhir.model.core.Procedure
resource.Provenance=org.hl7.fhir.model.core.Provenance
resource.Questionnaire=org.hl7.fhir.model.core.Questionnaire
resource.QuestionnaireResponse=org.hl7.fhir.model.core.QuestionnaireResponse
resource.RegulatedAuthorization=org.hl7.fhir.model.core.RegulatedAuthorization
resource.RelatedPerson=org.hl7.fhir.model.core.RelatedPerson
resource.RequestOrchestration=org.hl7.fhir.model.core.RequestOrchestration
resource.Requirements=org.hl7.fhir.model.core.Requirements
resource.ResearchStudy=org.hl7.fhir.model.core.ResearchStudy
resource.ResearchSubject=org.hl7.fhir.model.core.ResearchSubject
resource.RiskAssessment=org.hl7.fhir.model.core.RiskAssessment
resource.Schedule=org.hl7.fhir.model.core.Schedule
resource.SearchParameter=org.hl7.fhir.model.core.SearchParameter
resource.ServiceRequest=org.hl7.fhir.model.core.ServiceRequest
resource.Slot=org.hl7.fhir.model.core.Slot
resource.Specimen=org.hl7.fhir.model.core.Specimen
resource.SpecimenDefinition=org.hl7.fhir.model.core.SpecimenDefinition
resource.StructureDefinition=org.hl7.fhir.model.core.StructureDefinition
resource.Subscription=org.hl7.fhir.model.core.Subscription
resource.SubscriptionStatus=org.hl7.fhir.model.core.SubscriptionStatus
resource.SubscriptionTopic=org.hl7.fhir.model.core.SubscriptionTopic
resource.Substance=org.hl7.fhir.model.core.Substance
resource.SubstanceDefinition=org.hl7.fhir.model.core.SubstanceDefinition
resource.Task=org.hl7.fhir.model.core.Task
resource.TerminologyCapabilities=org.hl7.fhir.model.core.TerminologyCapabilities
resource.ValueSet=org.hl7.fhir.model.core.ValueSet
resource.VisionPrescription=org.hl7.fhir.model.core.VisionPrescription

datatype.Address=org.hl7.fhir.model.core.Address
datatype.Age=org.hl7.fhir.model.core.Age
datatype.Annotation=org.hl7.fhir.model.core.Annotation
datatype.Attachment=org.hl7.fhir.model.core.Attachment
datatype.Availability=org.hl7.fhir.model.core.Availability
datatype.BackboneType=org.hl7.fhir.model.core.BackboneType
datatype.CodeableConcept=org.hl7.fhir.model.core.CodeableConcept
datatype.CodeableReference=org.hl7.fhir.model.core.CodeableReference
datatype.Coding=org.hl7.fhir.model.core.Coding
datatype.ContactDetail=org.hl7.fhir.model.core.ContactDetail
datatype.ContactPoint=org.hl7.fhir.model.core.ContactPoint
datatype.Count=org.hl7.fhir.model.core.Count
datatype.DataRequirement=org.hl7.fhir.model.core.DataRequirement
datatype.DataType=org.hl7.fhir.model.core.DataType
datatype.Distance=org.hl7.fhir.model.core.Distance
datatype.Dosage=org.hl7.fhir.model.core.Dosage
datatype.DosageCondition=org.hl7.fhir.model.core.DosageCondition
datatype.DosageDetails=org.hl7.fhir.model.core.DosageDetails
datatype.DosageSafety=org.hl7.fhir.model.core.DosageSafety
datatype.Duration=org.hl7.fhir.model.core.Duration
datatype.ElementDefinition=org.hl7.fhir.model.core.ElementDefinition
datatype.Expression=org.hl7.fhir.model.core.Expression
datatype.ExtendedContactDetail=org.hl7.fhir.model.core.ExtendedContactDetail
datatype.Extension=org.hl7.fhir.model.core.Extension
datatype.HumanName=org.hl7.fhir.model.core.HumanName
datatype.Identifier=org.hl7.fhir.model.core.Identifier
datatype.MarketingStatus=org.hl7.fhir.model.core.MarketingStatus
datatype.Meta=org.hl7.fhir.model.core.Meta
datatype.MonetaryComponent=org.hl7.fhir.model.core.MonetaryComponent
datatype.Money=org.hl7.fhir.model.core.Money
datatype.Narrative=org.hl7.fhir.model.core.Narrative
datatype.ParameterDefinition=org.hl7.fhir.model.core.ParameterDefinition
datatype.Period=org.hl7.fhir.model.core.Period
datatype.ProductShelfLife=org.hl7.fhir.model.core.ProductShelfLife
datatype.Quantity=org.hl7.fhir.model.core.Quantity
datatype.Range=org.hl7.fhir.model.core.Range
datatype.Ratio=org.hl7.fhir.model.core.Ratio
datatype.RatioRange=org.hl7.fhir.model.core.RatioRange
datatype.Reference=org.hl7.fhir.model.core.Reference
datatype.RelatedArtifact=org.hl7.fhir.model.core.RelatedArtifact
datatype.RelativeTime=org.hl7.fhir.model.core.RelativeTime
datatype.SampledData=org.hl7.fhir.model.core.SampledData
datatype.Signature=org.hl7.fhir.model.core.Signature
datatype.SimpleQuantity=org.hl7.fhir.model.core.SimpleQuantity
datatype.Timing=org.hl7.fhir.model.core.Timing
datatype.TriggerDefinition=org.hl7.fhir.model.core.TriggerDefinition
datatype.UsageContext=org.hl7.fhir.model.core.UsageContext
datatype.VirtualServiceDetail=org.hl7.fhir.model.core.VirtualServiceDetail
datatype.base64Binary=org.hl7.fhir.model.core.Base64BinaryType
datatype.boolean=org.hl7.fhir.model.core.BooleanType
datatype.canonical=org.hl7.fhir.model.core.CanonicalType
datatype.code=org.hl7.fhir.model.core.CodeType
datatype.code.2=org.hl7.fhir.model.core.Enumeration
datatype.date=org.hl7.fhir.model.core.DateType
datatype.dateTime=org.hl7.fhir.model.core.DateTimeType
datatype.decimal=org.hl7.fhir.model.core.DecimalType
datatype.id=org.hl7.fhir.model.core.IdType
datatype.instant=org.hl7.fhir.model.core.InstantType
datatype.integer=org.hl7.fhir.model.core.IntegerType
datatype.integer64=org.hl7.fhir.model.core.Integer64Type
datatype.markdown=org.hl7.fhir.model.core.MarkdownType
datatype.oid=org.hl7.fhir.model.core.OidType
datatype.positiveInt=org.hl7.fhir.model.core.PositiveIntType
datatype.string=org.hl7.fhir.model.core.StringType
datatype.time=org.hl7.fhir.model.core.TimeType
datatype.unsignedInt=org.hl7.fhir.model.core.UnsignedIntType
datatype.uri=org.hl7.fhir.model.core.UriType
datatype.url=org.hl7.fhir.model.core.UrlType
datatype.uuid=org.hl7.fhir.model.core.UuidType
datatype.xhtml=org.hl7.fhir.utilities.xhtml.XhtmlNode
