# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# If you wish to automatically format your code on every commit,  please install this pre-commit hook by using the pre-commit framework, and running `pre-commit install`


repos:
-  repo: local
   hooks:
   -   id: maven-spotless-apply
       stages: [pre-push]
       name: Maven Spotless
       entry: mvn
       args: ['spotless:apply']
       language: system
       stages: ['pre-push']
       verbose: false
       always_run: true
       pass_filenames: false
