ignored_modules: >
  hapi-fhir-bom,hapi-deployable-pom,hapi-fhir-spring-boot,
  hapi-fhir-spring-boot-sample-client-apache,hapi-fhir-spring-boot-sample-client-okhttp,
  hapi-fhir-spring-boot-starter,hapi-fhir-spring-boot-samples,
  hapi-fhir-validation-resources-dstu2.1,hapi-fhir-structures-r4b,
  hapi-fhir-validation-resources-r4b,hapi-fhir-jpa,hapi-fhir-serviceloaders,
  hapi-fhir-storage-batch2-test-utilities,hapi-fhir-cli,hapi-fhir-dist,
  hapi-fhir-jacoco,hapi-fhir-server-cds-hooks,hapi-fhir-caching-testing,
  hapi-fhir-cli-app,hapi-fhir-karaf-features,hapi-fhir-karaf-integration-tests,osgi
