package ca.uhn.fhir.rest.client.interceptor;

public interface InterceptorOrders {

	int LOGGING_INTERCEPTOR_REQUEST = -2;
	int URL_TENANT_SELECTION_INTERCEPTOR_REQUEST = 100;
	int CAPTURING_INTERCEPTOR_REQUEST = 1000;

	int CAPTURING_INTERCEPTOR_RESPONSE = -1;
	int LOGGING_INTERCEPTOR_RESPONSE = 1001;
}
