---
type: add
issue: 5321
backport: 6.8.3
title: "It is now possible to configure the strictness of concept display name validation
   using a new flag on the InMemoryTerminologyServerValidationSupport (for non-JPA validation)
   and JpaStorageSettings (for JPA validation). In addition, the error messages emitted by
   the validator when a concept display doesn't match have been improved to be much
   more useful."
