name: Download and Process Artifacts
description: Downloads artifacts for a list of modules and prepares them for further steps.
inputs:
    modules:
        description: A JSON list of modules to process
        required: true
    github_token:
        description: GitHub token for API authentication
        required: true

runs:
    using: composite
    steps:

        - name: Download All Artifacts
          uses: actions/download-artifact@v4
          with:
              path: ./artifacts

        - name: Restore Artifacts to Original Locations
          shell: bash
          env:
              GH_TOKEN: ${{ inputs.github_token }}
          run: |
              echo "Restoring artifacts to original locations..."
              
              # Process each artifact in the downloaded directory
              for artifact_path in ./artifacts/*; do
                artifact=$(basename "$artifact_path")
                echo "Processing artifact: $artifact"
              
                # Replace underscores with slashes to get the original module path
                original_name=$(echo "$artifact" | sed 's|_|/|g')
                echo "Restoring original name: $original_name"
              
                # Target directory for the restored artifact
                target_dir="${original_name}"
              
                # Ensure the target directory exists
                mkdir -p "$(dirname "$target_dir")"
              
                # Move the artifact to the target directory
                mv "$artifact_path"/* "$target_dir"
              
                echo "Restored artifact for: $original_name"
              done
              
              echo "All artifacts have been restored to their original locations."

        - name: List All Directories and Subdirectories (Debug)
          shell: bash
          run: |
              TARGET_PATH="${GITHUB_WORKSPACE}"
              echo "Listing all directories and subdirectories under $TARGET_PATH:"
              find "$TARGET_PATH" -type d -exec ls -ld {} +
