name: Build and Test Maven Module
description: Build, test, and handle logs for a Maven module

inputs:
  java-version:
    description: 'Java version to use'
    required: false
    default: '17'
  maven-cache-folder:
    description: 'Folder path for Maven cache'
    required: true
    default: "$HOME/.m2/repository"
  module-name:
    description: 'The Maven module name to build'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'

    - name: Restore Maven Cache
      uses: ./.github/actions/caching-handler

    - name: Build Module ${{ inputs.module-name }}
      shell: bash
      env:
        MAVEN_CACHE_FOLDER: ${{ inputs.maven-cache-folder }}
        MAVEN_OPTS: '-Xmx1024m -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS -Duser.timezone=America/Toronto'
      run: |
        mvn clean verify jacoco:report -pl ${{ inputs.module-name }} \
          -P JACOCO,CI -e -B \
          -Dmaven.repo.local=$MAVEN_CACHE_FOLDER \
          -Dmaven.wagon.http.pool=false -Dhttp.keepAlive=false \
          -Dstyle.color=always -Djansi.force=true
      
    - name: Copy test log files
      shell: bash
      if: always()
      run: |
        mkdir -p ${{ github.workspace }}/artifacts
        find . -wholename '**/target/*-reports/*.txt' -exec cp {} ${{ github.workspace }}/artifacts \;

    - name: Clean Module Name
      id: clean_module_name
      shell: bash
      if: always()
      run: |
        module_name="${{ inputs.module-name }}"
        cleaned_name=$(basename "$module_name")
        echo "cleaned_name=$cleaned_name" >> $GITHUB_OUTPUT

    - name: Upload Full Test Logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ steps.clean_module_name.outputs.cleaned_name }}_full_logs_${{ github.run_id }}_${{ github.run_number }}
        path: ${{ github.workspace }}/artifacts

    - name: Publish Target Directory
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ steps.clean_module_name.outputs.cleaned_name }}_target
        path: ${{ github.workspace }}/${{ inputs.module-name }}/target
