# Note that this image is used only to publish HAPI-FHIR. this is published at `smilecdr/hapi-build`
# Start from the maven image
FROM maven:3.9-eclipse-temurin-21-jammy

# Install gpg
RUN apt-get update && apt-get install -y gpg
