<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>ca.uhn.hapi.fhir</groupId>
		<artifactId>hapi-fhir</artifactId>
		<version>8.13.9-SNAPSHOT</version>
	</parent>

	<artifactId>hapi-fhir-structures-normative</artifactId>

	<dependencies>
		<dependency>
			<groupId>ca.uhn.hapi.fhir</groupId>
			<artifactId>hapi-fhir-base</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>ca.uhn.hapi.fhir</groupId>
			<artifactId>hapi-fhir-caching-api</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>ca.uhn.hapi.fhir</groupId>
			<artifactId>hapi-fhir-server</artifactId>
			<version>${project.version}</version>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>ca.uhn.hapi.fhir</groupId>
			<artifactId>org.hl7.fhir.utilities</artifactId>
			<version>${fhir_core_version}</version>
		</dependency>
		<dependency>
			<groupId>ca.uhn.hapi.fhir</groupId>
			<artifactId>org.hl7.fhir.model</artifactId>
			<version>${fhir_core_version}</version>
		</dependency>
		<dependency>
			<groupId>ca.uhn.hapi.fhir</groupId>
			<artifactId>org.hl7.fhir.services</artifactId>
			<version>${fhir_core_version}</version>
		</dependency>

		<!-- Test Deps -->
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<optional>true</optional>
			<scope>test</scope>
		</dependency>


	</dependencies>

	<reporting>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<configuration>
					<show>public</show>
					<includeDependencySources>true</includeDependencySources>
					<dependencySourceIncludes>
						<include>ca.uhn.hapi.fhir:org.hl7.fhir.model</include>
					</dependencySourceIncludes>
					<additionalDependencies>
						<dependency>
							<groupId>com.squareup.okhttp3</groupId>
							<artifactId>okhttp</artifactId>
							<version>${okhttp_version}</version>
						</dependency>
						<dependency>
							<groupId>com.github.spotbugs</groupId>
							<artifactId>spotbugs-annotations</artifactId>
							<version>${spotbugs_annotations_version}</version>
						</dependency>
					</additionalDependencies>
				</configuration>
			</plugin>
		</plugins>
	</reporting>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>license-maven-plugin</artifactId>
				<configuration>
					<!-- Don't add UHN licenses to RI structures -->
					<skipUpdateLicense>true</skipUpdateLicense>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<extensions>true</extensions>
				<configuration>
					<instructions>
						<_nouses>true</_nouses>
						<_removeheaders>Built-By, Include-Resource, Private-Package, Require-Capability</_removeheaders>
						<!-- No need to disable normal OSGi class loading
				<Fragment-Host>
					ca.uhn.hapi.fhir.hapi-fhir-base
				</Fragment-Host>
				-->
					</instructions>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<configuration>
					<includeDependencySources>true</includeDependencySources>
					<dependencySourceIncludes>
						<include>ca.uhn.hapi.fhir:org.hl7.fhir.r5</include>
					</dependencySourceIncludes>
					<additionalDependencies>
						<dependency>
							<groupId>com.google.guava</groupId>
							<artifactId>guava</artifactId>
							<version>${guava_version}</version>
						</dependency>
						<dependency>
							<groupId>com.squareup.okhttp3</groupId>
							<artifactId>okhttp</artifactId>
							<version>${okhttp_version}</version>
						</dependency>
						<dependency>
							<groupId>com.github.spotbugs</groupId>
							<artifactId>spotbugs-annotations</artifactId>
							<version>${spotbugs_annotations_version}</version>
						</dependency>
					</additionalDependencies>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>CI</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>animal-sniffer-maven-plugin</artifactId>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

</project>
