package ca.uhn.fhir.jpa.ips.api;

public enum IpsSectionEnum {
		ALLERGY_INTOLERANCE,
		MEDICATION_SUMMARY,
		PROBLEM_LIST,
		IMMUNIZATIONS,
		PROCEDURES,
		MEDICAL_DEVICES,
		DIAGNOSTIC_RESULTS,
		VITAL_SIGNS,
		ILLNESS_HISTORY,
		PREGNANCY,
		SOCIAL_HISTORY,
		FUNCTIONAL_STATUS,
		PLAN_OF_CARE,
		ADVANCE_DIRECTIVES
	}
