package ca.uhn.fhir.jpa.subscription.model;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class DebeziumMessageTest {

	@Test
	public void testMessageDeserializes() throws IOException {
		String s = "{\n" +
			"   \"schema\":{\n" +
			"      \"type\":\"struct\",\n" +
			"      \"fields\":[\n" +
			"         {\n" +
			"            \"type\":\"struct\",\n" +
			"            \"fields\":[\n" +
			"               {\n" +
			"                  \"type\":\"int64\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"PID\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int32\",\n" +
			"                  \"optional\":True,\n" +
			"                  \"name\":\"io.debezium.time.Date\",\n" +
			"                  \"version\":1,\n" +
			"                  \"field\":\"PARTITION_DATE\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int32\",\n" +
			"                  \"optional\":True,\n" +
			"                  \"field\":\"PARTITION_ID\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int64\",\n" +
			"                  \"optional\":True,\n" +
			"                  \"name\":\"io.debezium.time.NanoTimestamp\",\n" +
			"                  \"version\":1,\n" +
			"                  \"field\":\"RES_DELETED_AT\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"string\",\n" +
			"                  \"optional\":True,\n" +
			"                  \"field\":\"RES_VERSION\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"boolean\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"HAS_TAGS\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int64\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"name\":\"io.debezium.time.NanoTimestamp\",\n" +
			"                  \"version\":1,\n" +
			"                  \"field\":\"RES_PUBLISHED\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int64\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"name\":\"io.debezium.time.NanoTimestamp\",\n" +
			"                  \"version\":1,\n" +
			"                  \"field\":\"RES_UPDATED\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"string\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"RES_ENCODING\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"bytes\",\n" +
			"                  \"optional\":True,\n" +
			"                  \"field\":\"RES_TEXT\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int64\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"RES_ID\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"string\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"RES_TYPE\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int64\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"RES_VER\"\n" +
			"               }\n" +
			"            ],\n" +
			"            \"optional\":True,\n" +
			"            \"name\":\"mssql_events.dbo.HFJ_RES_VER.Value\",\n" +
			"            \"field\":\"before\"\n" +
			"         },\n" +
			"         {\n" +
			"            \"type\":\"struct\",\n" +
			"            \"fields\":[\n" +
			"               {\n" +
			"                  \"type\":\"int64\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"PID\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int32\",\n" +
			"                  \"optional\":True,\n" +
			"                  \"name\":\"io.debezium.time.Date\",\n" +
			"                  \"version\":1,\n" +
			"                  \"field\":\"PARTITION_DATE\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int32\",\n" +
			"                  \"optional\":True,\n" +
			"                  \"field\":\"PARTITION_ID\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int64\",\n" +
			"                  \"optional\":True,\n" +
			"                  \"name\":\"io.debezium.time.NanoTimestamp\",\n" +
			"                  \"version\":1,\n" +
			"                  \"field\":\"RES_DELETED_AT\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"string\",\n" +
			"                  \"optional\":True,\n" +
			"                  \"field\":\"RES_VERSION\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"boolean\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"HAS_TAGS\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int64\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"name\":\"io.debezium.time.NanoTimestamp\",\n" +
			"                  \"version\":1,\n" +
			"                  \"field\":\"RES_PUBLISHED\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int64\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"name\":\"io.debezium.time.NanoTimestamp\",\n" +
			"                  \"version\":1,\n" +
			"                  \"field\":\"RES_UPDATED\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"string\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"RES_ENCODING\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"bytes\",\n" +
			"                  \"optional\":True,\n" +
			"                  \"field\":\"RES_TEXT\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int64\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"RES_ID\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"string\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"RES_TYPE\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int64\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"RES_VER\"\n" +
			"               }\n" +
			"            ],\n" +
			"            \"optional\":True,\n" +
			"            \"name\":\"mssql_events.dbo.HFJ_RES_VER.Value\",\n" +
			"            \"field\":\"after\"\n" +
			"         },\n" +
			"         {\n" +
			"            \"type\":\"struct\",\n" +
			"            \"fields\":[\n" +
			"               {\n" +
			"                  \"type\":\"string\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"version\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"string\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"connector\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"string\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"name\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int64\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"ts_ms\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"string\",\n" +
			"                  \"optional\":True,\n" +
			"                  \"name\":\"io.debezium.data.Enum\",\n" +
			"                  \"version\":1,\n" +
			"                  \"parameters\":{\n" +
			"                     \"allowed\":\"true,last,false\"\n" +
			"                  },\n" +
			"                  \"default\":\"false\",\n" +
			"                  \"field\":\"snapshot\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"string\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"db\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"string\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"schema\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"string\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"table\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"string\",\n" +
			"                  \"optional\":True,\n" +
			"                  \"field\":\"change_lsn\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"string\",\n" +
			"                  \"optional\":True,\n" +
			"                  \"field\":\"commit_lsn\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int64\",\n" +
			"                  \"optional\":True,\n" +
			"                  \"field\":\"event_serial_no\"\n" +
			"               }\n" +
			"            ],\n" +
			"            \"optional\":False,\n" +
			"            \"name\":\"io.debezium.connector.sqlserver.Source\",\n" +
			"            \"field\":\"source\"\n" +
			"         },\n" +
			"         {\n" +
			"            \"type\":\"string\",\n" +
			"            \"optional\":False,\n" +
			"            \"field\":\"op\"\n" +
			"         },\n" +
			"         {\n" +
			"            \"type\":\"int64\",\n" +
			"            \"optional\":True,\n" +
			"            \"field\":\"ts_ms\"\n" +
			"         },\n" +
			"         {\n" +
			"            \"type\":\"struct\",\n" +
			"            \"fields\":[\n" +
			"               {\n" +
			"                  \"type\":\"string\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"id\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int64\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"total_order\"\n" +
			"               },\n" +
			"               {\n" +
			"                  \"type\":\"int64\",\n" +
			"                  \"optional\":False,\n" +
			"                  \"field\":\"data_collection_order\"\n" +
			"               }\n" +
			"            ],\n" +
			"            \"optional\":True,\n" +
			"            \"field\":\"transaction\"\n" +
			"         }\n" +
			"      ],\n" +
			"      \"optional\":False,\n" +
			"      \"name\":\"mssql_events.dbo.HFJ_RES_VER.Envelope\"\n" +
			"   },\n" +
			"   \"payload\":{\n" +
			"      \"before\":\"None\",\n" +
			"      \"after\":{\n" +
			"         \"PID\":1624,\n" +
			"         \"PARTITION_DATE\":\"None\",\n" +
			"         \"PARTITION_ID\":\"None\",\n" +
			"         \"RES_DELETED_AT\":\"None\",\n" +
			"         \"RES_VERSION\":\"R4\",\n" +
			"         \"HAS_TAGS\":False,\n" +
			"         \"RES_PUBLISHED\":1598375747709000000,\n" +
			"         \"RES_UPDATED\":1598375747709000000,\n" +
			"         \"RES_ENCODING\":\"JSONC\",\n" +
			"         \"RES_TEXT\":\"H4sIAAAAAAAAAD2OTQ7CUAiEr0JYNx7AM7gw0Z1xgZSmpFpegPoT4919TavLGYZv5o0uYZOzHF9FcIsHIed+T043SXFsMJJyinoiTr1LdVoJdi2pNv4/JKAzh6sxzX7AQ7MHgijC2inDoGML1sGKa5CtnQv/+kJR9Ql3KwLPDeYyKm2QsUbkWercWHp/uc1K+HwBQO9LzMwAAAA=\",\n" +
			"         \"RES_ID\":1624,\n" +
			"         \"RES_TYPE\":\"SearchParameter\",\n" +
			"         \"RES_VER\":1\n" +
			"      },\n" +
			"      \"source\":{\n" +
			"         \"version\":\"1.2.0.Final\",\n" +
			"         \"connector\":\"sqlserver\",\n" +
			"         \"name\":\"mssql_events\",\n" +
			"         \"ts_ms\":1598376255646,\n" +
			"         \"snapshot\":\"last\",\n" +
			"         \"db\":\"cdr\",\n" +
			"         \"schema\":\"dbo\",\n" +
			"         \"table\":\"HFJ_RES_VER\",\n" +
			"         \"change_lsn\":\"None\",\n" +
			"         \"commit_lsn\":\"None\",\n" +
			"         \"event_serial_no\":\"None\"\n" +
			"      },\n" +
			"      \"op\":\"r\",\n" +
			"      \"ts_ms\":1598376255646,\n" +
			"      \"transaction\":\"None\"\n"+
			"   }\n" +
			"}";

		ObjectMapper mapper = new ObjectMapper();
		DebeziumMessage debeziumMessage = mapper.reader().readValue(s, DebeziumMessage.class);
		System.out.println(debeziumMessage.getResourceBytes());
		assert debeziumMessage != null;
	}
}
