package ca.uhn.fhir.jpa.term.api;

import ca.uhn.fhir.jpa.entity.TermValueSetConcept;
import ca.uhn.fhir.jpa.entity.TermValueSetPreExpansionStatusEnum;
import ca.uhn.fhir.jpa.model.entity.ResourceTable;
import ca.uhn.fhir.jpa.term.UploadStatistics;
import ca.uhn.fhir.rest.api.server.RequestDetails;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import org.hl7.fhir.instance.model.api.IIdType;
import org.hl7.fhir.r4.model.ValueSet;

public interface ITermValueSetStorageSvc {

	/**
	 * Creates a new staging version of the given ValueSet, intended for
	 * pre-expanding concepts. The existing version will be marked with status
	 * {@link TermValueSetPreExpansionStatusEnum#EXPANSION_IN_PROGRESS}.
	 * The staging version will be assigned a random UUID version which will
	 * be replaced by the intended version when the staging is complete.
	 *
	 * @param theUrl The ValueSet URI (must not be a versioned URI)
	 * @param theVersion The ValueSet version (can be null)
	 * @return Returns a staging version string
	 * @since 8.12.0
	 */
	@Nonnull
	String startStagingVersion(@Nonnull String theUrl, @Nullable String theVersion);

	/**
	 * Adds concepts to the precalculated expansion of the given ValueSet, using
	 * the <code>ValueSet.url</code> and <code>ValueSet.version</code> to identify
	 * the ValueSet to add to. The concepts in <code>ValueSet.expansion</code>
	 * will be added if they are not already present.
	 *
	 * @param theDelta The ValueSet to add
	 * @param theStartingOrder The index {@link TermValueSetConcept#getOrder()} to use for the first concept added, and incrementing by one for each code.
	 * @return Returns an object containing statistics about what was added
	 */
	@Nonnull
	UploadStatistics addConceptsToExpansion(@Nonnull ValueSet theDelta, int theStartingOrder);

	/**
	 * Adds concepts to the precalculated expansion of the given ValueSet, using
	 * the <code>ValueSet.url</code> and <code>ValueSet.version</code> to identify
	 * the ValueSet to add to. The concepts in <code>ValueSet.expansion</code>
	 * will be removed if they are already present. Any codes specified for removal
	 * that are not actually present in the expansion will be ignored.
	 *
	 * @param theDelta The ValueSet to remove
	 * @return Returns an object containing statistics about what was added
	 */
	@Nonnull
	UploadStatistics removeConceptsFromExpansion(ValueSet theDelta);

	/**
	 * Takes a ValueSet that is being staged (see {@link #startStagingVersion(String, String)})
	 * and activates it so that it becomes the active version.
	 *
	 * @param theValueSetUrl The ValueSet URL
	 * @param theStagingVersionId The staging version ID
	 * @since 8.12.0
	 */
	void activateStagingVersion(String theValueSetUrl, String theStagingVersionId);

	/**
	 * Drops a ValueSet that is being staged (see {@link #startStagingVersion(String, String)}),
	 * deleting all files associated with it.
	 *
	 * @param theValueSetUrl The ValueSet URL
	 * @param theStagingVersionId The staging version ID
	 * @since 8.12.0
	 */
	void dropStagingVersion(String theValueSetUrl, String theStagingVersionId);

	/**
	 * Deletes any stored ValueSet pre-expansion content related to the given ValueSet resource
	 */
	void deleteValueSetAndChildren(ResourceTable theResourceTable);

	/**
	 * Creates a new ValueSet entity linked to a ValueSet resource
	 */
	void storeTermValueSet(
			RequestDetails theRequestDetails,
			ResourceTable theResourceTable,
			org.hl7.fhir.r4.model.ValueSet theValueSet);

	/**
	 * Invalidates pre-calculated expansions for all ValueSets whose expansions contain
	 * concepts from the given CodeSystem URL. Should be called whenever a CodeSystem is
	 * created or updated so that stale expansions are not used for code validation.
	 *
	 * @param theCodeSystemUrl the URL of the updated CodeSystem
	 * @return the number of ValueSet expansions that were invalidated
	 * @generated by claude-sonnet-4-6
	 */
	int invalidatePreCalculatedExpansionOfValueSetsContainingCodeSystem(String theCodeSystemUrl);

	/**
	 * Set the expansion status of the given ValueSet to {@link TermValueSetPreExpansionStatusEnum#FAILED_TO_EXPAND}
	 *
	 * @param theUrl The ValueSet URL
	 * @param theVersion The ValueSet version
	 * @since 8.12.0
	 */
	void markValueSetAsFailedToExpand(String theUrl, String theVersion);
}
