/*-
 * #%L
 * HAPI FHIR JPA Server
 * %%
 * Copyright (C) 2014 - 2026 Smile CDR, Inc.
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package ca.uhn.fhir.jpa.term.api;

import ca.uhn.fhir.jpa.entity.TermCodeSystemVersion;
import ca.uhn.fhir.jpa.entity.TermConcept;
import ca.uhn.fhir.jpa.model.dao.JpaPid;
import ca.uhn.fhir.jpa.model.entity.ResourceTable;
import ca.uhn.fhir.jpa.term.UploadStatistics;
import ca.uhn.fhir.rest.api.server.RequestDetails;
import jakarta.annotation.Nullable;
import org.hl7.fhir.instance.model.api.IBaseResource;
import org.hl7.fhir.instance.model.api.IIdType;
import org.hl7.fhir.r4.model.ValueSet;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * This service handles writes to the CodeSystem/Concept tables within the terminology services
 */
public interface ITermCodeSystemStorageSvc {

	String MAKE_LOADING_VERSION_CURRENT = "make.loading.version.current";

	/**
	 * Defaults to true when the parameter is null or entry is not present in requestDetails.myUserData
	 */
	static boolean isMakeVersionCurrent(RequestDetails theRequestDetails) {
		return theRequestDetails == null
				|| (boolean) theRequestDetails.getUserData().getOrDefault(MAKE_LOADING_VERSION_CURRENT, Boolean.TRUE);
	}

	void storeNewCodeSystemVersion(
			String theSystemUri,
			String theSystemName,
			String theSystemVersionId,
			TermCodeSystemVersion theCodeSystemVersion,
			ResourceTable theCodeSystemResourceTable,
			RequestDetails theRequestDetails);

	/**
	 * The default implementation supports the previous signature of the method which was added RequestDetails parameter
	 */
	@Transactional
	default void storeNewCodeSystemVersion(
			String theSystemUri,
			String theSystemName,
			String theSystemVersionId,
			TermCodeSystemVersion theCodeSystemVersion,
			ResourceTable theCodeSystemResourceTable) {

		storeNewCodeSystemVersion(
				theSystemUri,
				theSystemName,
				theSystemVersionId,
				theCodeSystemVersion,
				theCodeSystemResourceTable,
				null);
	}

	/**
	 * @return Returns the ID of the created/updated code system
	 */
	IIdType storeNewCodeSystemVersion(
			org.hl7.fhir.r4.model.CodeSystem theCodeSystemResource,
			TermCodeSystemVersion theCodeSystemVersion,
			RequestDetails theRequestDetails,
			List<ValueSet> theValueSets,
			List<org.hl7.fhir.r4.model.ConceptMap> theConceptMaps);

	void storeNewCodeSystemVersionIfNeeded(
			IBaseResource theCodeSystem, ResourceTable theResourceEntity, RequestDetails theRequestDetails);

	/**
	 * The default implementation supports the previous signature of the method which was added RequestDetails parameter
	 */
	default void storeNewCodeSystemVersionIfNeeded(IBaseResource theCodeSystem, ResourceTable theResourceEntity) {
		storeNewCodeSystemVersionIfNeeded(theCodeSystem, theResourceEntity, null);
	}

	/**
	 * Looks up the FHIR resource PID of an existing CodeSystem in the terminology tables
	 * by {@code (url, version)}. Returns {@link Optional#empty()} when no matching
	 * {@code TRM_CODESYSTEM_VER} row exists.
	 *
	 * @param theUrl     the {@code CodeSystem.url} to look up
	 * @param theVersion the {@code CodeSystem.version} to match, or {@code null} for unversioned
	 * @return the resource PID if found
	 */
	// Generated by Claude Opus 4.6
	Optional<JpaPid> findExistingCodeSystemResourcePid(String theUrl, @Nullable String theVersion);

	int saveConcept(TermConcept theNextConcept);

	/**
	 * Prepares a code system version for staging, meaning that it is ready to begin accepting
	 * new codes, properties, relationships, etc. This method will create the new version
	 * if one does not already exist but will leave the existing one untouched if it does.
	 * <p>
	 * The new version will not be activated if it is not already active, meaning that you can
	 * add codes through one or more calls to {@link #addCodeSystemConcepts(RequestDetails, IBaseResource)}
	 * without those new codes being available for validation. Once all codes have been staged,
	 * you can activate the new version by calling {@link #activateStagingCodeSystemVersion(String, String, boolean)}.
	 * </p>
	 *
	 * @since 8.12.0
	 */
	StartStagingCodeSystemVersionResponse startStagingCodeSystemVersion(String theCodeSystemUrl, String theVersionId);

	/**
	 * Uploads concepts from a CodeSystem resource to the database. This method uses a CodeSystem
	 * resource as the transport container for the concepts but does not actually store the
	 * actual CodeSystem resource, it just adds the concepts to the terminology database. The
	 * {@literal CodeSystem.url} and {@literal CodeSystem.version} properties must be populated.
	 * <p>
	 * Note that the concept parents {@link TermConcept#getParents()} are not populated by this
	 * method. And must be explicitly populated by the caller.
	 * </p>
	 *
	 * @since 8.12.0
	 */
	// TODO: Currently the only way to populate the getParents() is an inline step in the LOINC
	// import job. We need to refactor that out.
	UploadStatistics addCodeSystemConcepts(RequestDetails theRequestDetails, IBaseResource theCodeSystem);

	/**
	 * Removes concepts from a content=not-present CodeSystem in the database.
	 *
	 * @since 8.2.0
	 */
	UploadStatistics removeCodeSystemConcepts(RequestDetails theRequestDetails, IBaseResource theCodeSystem);

	/**
	 * Takes a CodeSystemVersion that is being staged (see {@link #startStagingCodeSystemVersion(String, String)})
	 * and activates it so that it can be used for code validation.
	 * When {@link #startStagingCodeSystemVersion(String, String)} is called, the intended
	 * version is specified, but at that time we assign a temporary ID to the staging version,
	 * and remember the version that is intended to be used once activated. When this method
	 * is called, we change the version to the actual intended version. If a version
	 * already exists with the same URL and version, it will be deleted.
	 *
	 * @param theCodeSystemUrl The code system URL
	 * @param theStagingVersionId The staging version ID
	 * @param theMakeCurrent Should the given version be made the current version? Note that if this
	 *                       method would result in the current version being deleted, we will make the
	 *                       staging version the current version regardless of this parameter.
	 * @since 8.12.0
	 */
	void activateStagingCodeSystemVersion(String theCodeSystemUrl, String theStagingVersionId, boolean theMakeCurrent);

	/**
	 * @param stagingVersionId A temporary ID associated with the version that is being staged
	 */
	record StartStagingCodeSystemVersionResponse(String stagingVersionId) {}
}
