package ca.uhn.fhir.interceptor.model;

import ca.uhn.fhir.rest.api.RestOperationTypeEnum;
import ca.uhn.fhir.rest.api.server.SystemRequestDetails;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

// Created by claude-sonnet-4-6
class ReadPartitionIdRequestDetailsTest {

	/**
	 * Regression test for https://github.com/hapifhir/hapi-fhir/issues/7681
	 * <p>
	 * {@link SystemRequestDetails} has no REST operation type. Passing it to
	 * {@link ReadPartitionIdRequestDetails#forGeneric} must not produce a null
	 * {@code restOperationType}, otherwise partition interceptors that switch on
	 * that value will throw a {@link NullPointerException}.
	 */
	@Test
	// Generated by claude-sonnet-4-6
	void testForGeneric_WithSystemRequestDetails_DefaultsOperationType() {
		ReadPartitionIdRequestDetails details = ReadPartitionIdRequestDetails.forGeneric(new SystemRequestDetails());

		assertThat(details.getRestOperationType())
				.as("restOperationType must not be null for system requests")
				.isEqualTo(RestOperationTypeEnum.EXTENDED_OPERATION_SERVER);
	}
}
