package ca.uhn.fhir.interceptor.model;

import ca.uhn.fhir.rest.api.server.SystemRequestDetails;
import ca.uhn.fhir.rest.server.provider.ProviderConstants;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

// Created by claude-sonnet-4-6
class ReadPartitionIdRequestDetailsTest {

	@Test
	// Generated by claude-sonnet-4-6
	void testForGeneric_WithOperationSet_PassesThroughOperationName() {
		SystemRequestDetails request = new SystemRequestDetails();
		request.setOperation(ProviderConstants.MDM_LINK_HISTORY);

		ReadPartitionIdRequestDetails details = ReadPartitionIdRequestDetails.forGeneric(request);

		assertThat(details.getExtendedOperationName()).isEqualTo(ProviderConstants.MDM_LINK_HISTORY);
	}
}
