// Generated from FhirMapJava.g4 by ANTLR 4.7

  package org.hl7.fhir.r4.utils.transform.deserializer.grammar.antlr.javaAntlr;

import org.antlr.v4.runtime.Lexer;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.TokenStream;
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.atn.*;
import org.antlr.v4.runtime.dfa.DFA;
import org.antlr.v4.runtime.misc.*;

/**
 * Lexer gereated by ANTLR, modify with care
 */
@SuppressWarnings({"all", "warnings", "unchecked", "unused", "cast"})
public class FhirMapJavaLexer extends Lexer {
	static { RuntimeMetaData.checkVersion("4.7", RuntimeMetaData.VERSION); }


	protected static final DFA[] _decisionToDFA;
	protected static final PredictionContextCache _sharedContextCache =
		new PredictionContextCache();
	public static final int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, HEX=12, DIGITS=13, SOURCE=14, TARGET=15, QUERIED=16, 
		PRODUCED=17, QIDENTIFIER=18, QSTRING=19, APPEND=20, AS=21, CAST=22, C=23, 
		CC=24, CODE=25, CP=26, CHECK=27, CODEABLECONCEPT=28, CODING=29, COPY=30, 
		CREATE=31, DATEOP=32, DEFAULT=33, DISPLAY=34, ENDGROUP=35, ESCAPE=36, 
		EVALUATE=37, EXTENDS=38, FOR=39, GROUP=40, ID=41, IMPORTS=42, INPUT=43, 
		MAKE=44, MAP=45, POINTER=46, QTY=47, REFERENCE=48, SYSTEM=49, THEN=50, 
		TRANSLATE=51, TRUNCATE=52, TYPES=53, TYPE_TYPES=54, UUID=55, USES=56, 
		WHERE=57, IDENTIFIER=58, WS=59, LINE_COMMENT=60;
	public static String[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static String[] modeNames = {
		"DEFAULT_MODE"
	};

  /**
   * Array of rule names generated by ANTLR
   */
	public static final String[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "DIGIT_FRAG", "HEX_FRAG", "LETTER_FRAG", "HEX", "DIGITS", 
		"SOURCE", "TARGET", "QUERIED", "PRODUCED", "QIDENTIFIER", "QSTRING", "APPEND", 
		"AS", "CAST", "C", "CC", "CODE", "CP", "CHECK", "CODEABLECONCEPT", "CODING", 
		"COPY", "CREATE", "DATEOP", "DEFAULT", "DISPLAY", "ENDGROUP", "ESCAPE", 
		"EVALUATE", "EXTENDS", "FOR", "GROUP", "ID", "IMPORTS", "INPUT", "MAKE", 
		"MAP", "POINTER", "QTY", "REFERENCE", "SYSTEM", "THEN", "TRANSLATE", "TRUNCATE", 
		"TYPES", "TYPE_TYPES", "UUID", "USES", "WHERE", "IDENTIFIER", "WS", "LINE_COMMENT"
	};

	private static final String[] _LITERAL_NAMES = {
		null, "'='", "';'", "':'", "'.'", "','", "'..'", "'xxxxyyyyyzzzzzz'", 
		"'{'", "'}'", "'('", "')'", null, null, "'source'", "'target'", "'queried'", 
		"'produced'", null, null, "'append'", "'as'", "'cast'", "'c'", "'cc'", 
		"'code'", "'cp'", "'check'", "'codeableConcept'", "'coding'", "'copy'", 
		"'create'", "'dateOp'", "'default'", "'display'", "'endgroup'", "'escape'", 
		"'evaluate'", "'extends'", "'for'", "'group'", "'id'", "'imports'", "'input'", 
		"'make'", "'map'", "'pointer'", "'qty'", "'reference'", "'system'", "'then'", 
		"'translate'", "'truncate'", "'types'", "'type+types'", "'uuid'", "'uses'", 
		"'where'"
	};
	private static final String[] _SYMBOLIC_NAMES = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		"HEX", "DIGITS", "SOURCE", "TARGET", "QUERIED", "PRODUCED", "QIDENTIFIER", 
		"QSTRING", "APPEND", "AS", "CAST", "C", "CC", "CODE", "CP", "CHECK", "CODEABLECONCEPT", 
		"CODING", "COPY", "CREATE", "DATEOP", "DEFAULT", "DISPLAY", "ENDGROUP", 
		"ESCAPE", "EVALUATE", "EXTENDS", "FOR", "GROUP", "ID", "IMPORTS", "INPUT", 
		"MAKE", "MAP", "POINTER", "QTY", "REFERENCE", "SYSTEM", "THEN", "TRANSLATE", 
		"TRUNCATE", "TYPES", "TYPE_TYPES", "UUID", "USES", "WHERE", "IDENTIFIER", 
		"WS", "LINE_COMMENT"
	};
	public static final Vocabulary VOCABULARY = new VocabularyImpl(_LITERAL_NAMES, _SYMBOLIC_NAMES);

	/**
	 * @deprecated Use {@link #VOCABULARY} instead.
	 */
	@Deprecated
	public static final String[] tokenNames;
	static {
		tokenNames = new String[_SYMBOLIC_NAMES.length];
		for (int i = 0; i < tokenNames.length; i++) {
			tokenNames[i] = VOCABULARY.getLiteralName(i);
			if (tokenNames[i] == null) {
				tokenNames[i] = VOCABULARY.getSymbolicName(i);
			}

			if (tokenNames[i] == null) {
				tokenNames[i] = "<INVALID>";
			}
		}
	}

	@Override
	@Deprecated
	public String[] getTokenNames() {
		return tokenNames;
	}

	@Override

	public Vocabulary getVocabulary() {
		return VOCABULARY;
	}


	public FhirMapJavaLexer(CharStream input) {
		super(input);
		_interp = new LexerATNSimulator(this,_ATN,_decisionToDFA,_sharedContextCache);
	}

	@Override
	public String getGrammarFileName() { return "FhirMapJava.g4"; }

	@Override
	public String[] getRuleNames() { return ruleNames; }

	@Override
	public String getSerializedATN() { return _serializedATN; }

	@Override
	public String[] getChannelNames() { return channelNames; }

	@Override
	public String[] getModeNames() { return modeNames; }

	@Override
	public ATN getATN() { return _ATN; }

	public static final String _serializedATN =
		"\3\u608b\ua72a\u8133\ub9ed\u417c\u3be7\u7786\u5964\2>\u01fd\b\1\4\2\t"+
		"\2\4\3\t\3\4\4\t\4\4\5\t\5\4\6\t\6\4\7\t\7\4\b\t\b\4\t\t\t\4\n\t\n\4\13"+
		"\t\13\4\f\t\f\4\r\t\r\4\16\t\16\4\17\t\17\4\20\t\20\4\21\t\21\4\22\t\22"+
		"\4\23\t\23\4\24\t\24\4\25\t\25\4\26\t\26\4\27\t\27\4\30\t\30\4\31\t\31"+
		"\4\32\t\32\4\33\t\33\4\34\t\34\4\35\t\35\4\36\t\36\4\37\t\37\4 \t \4!"+
		"\t!\4\"\t\"\4#\t#\4$\t$\4%\t%\4&\t&\4\'\t\'\4(\t(\4)\t)\4*\t*\4+\t+\4"+
		",\t,\4-\t-\4.\t.\4/\t/\4\60\t\60\4\61\t\61\4\62\t\62\4\63\t\63\4\64\t"+
		"\64\4\65\t\65\4\66\t\66\4\67\t\67\48\t8\49\t9\4:\t:\4;\t;\4<\t<\4=\t="+
		"\4>\t>\4?\t?\4@\t@\3\2\3\2\3\3\3\3\3\4\3\4\3\5\3\5\3\6\3\6\3\7\3\7\3\7"+
		"\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\t\3"+
		"\t\3\n\3\n\3\13\3\13\3\f\3\f\3\r\3\r\3\16\3\16\3\17\3\17\3\20\3\20\3\20"+
		"\6\20\u00b0\n\20\r\20\16\20\u00b1\3\21\6\21\u00b5\n\21\r\21\16\21\u00b6"+
		"\3\22\3\22\3\22\3\22\3\22\3\22\3\22\3\23\3\23\3\23\3\23\3\23\3\23\3\23"+
		"\3\24\3\24\3\24\3\24\3\24\3\24\3\24\3\24\3\25\3\25\3\25\3\25\3\25\3\25"+
		"\3\25\3\25\3\25\3\26\3\26\3\26\3\26\3\26\3\26\7\26\u00de\n\26\f\26\16"+
		"\26\u00e1\13\26\3\26\3\26\3\27\3\27\7\27\u00e7\n\27\f\27\16\27\u00ea\13"+
		"\27\3\27\3\27\3\30\3\30\3\30\3\30\3\30\3\30\3\30\3\31\3\31\3\31\3\32\3"+
		"\32\3\32\3\32\3\32\3\33\3\33\3\34\3\34\3\34\3\35\3\35\3\35\3\35\3\35\3"+
		"\36\3\36\3\36\3\37\3\37\3\37\3\37\3\37\3\37\3 \3 \3 \3 \3 \3 \3 \3 \3"+
		" \3 \3 \3 \3 \3 \3 \3 \3!\3!\3!\3!\3!\3!\3!\3\"\3\"\3\"\3\"\3\"\3#\3#"+
		"\3#\3#\3#\3#\3#\3$\3$\3$\3$\3$\3$\3$\3%\3%\3%\3%\3%\3%\3%\3%\3&\3&\3&"+
		"\3&\3&\3&\3&\3&\3\'\3\'\3\'\3\'\3\'\3\'\3\'\3\'\3\'\3(\3(\3(\3(\3(\3("+
		"\3(\3)\3)\3)\3)\3)\3)\3)\3)\3)\3*\3*\3*\3*\3*\3*\3*\3*\3+\3+\3+\3+\3,"+
		"\3,\3,\3,\3,\3,\3-\3-\3-\3.\3.\3.\3.\3.\3.\3.\3.\3/\3/\3/\3/\3/\3/\3\60"+
		"\3\60\3\60\3\60\3\60\3\61\3\61\3\61\3\61\3\62\3\62\3\62\3\62\3\62\3\62"+
		"\3\62\3\62\3\63\3\63\3\63\3\63\3\64\3\64\3\64\3\64\3\64\3\64\3\64\3\64"+
		"\3\64\3\64\3\65\3\65\3\65\3\65\3\65\3\65\3\65\3\66\3\66\3\66\3\66\3\66"+
		"\3\67\3\67\3\67\3\67\3\67\3\67\3\67\3\67\3\67\3\67\38\38\38\38\38\38\3"+
		"8\38\38\39\39\39\39\39\39\3:\3:\3:\3:\3:\3:\3:\3:\3:\3:\3:\3;\3;\3;\3"+
		";\3;\3<\3<\3<\3<\3<\3=\3=\3=\3=\3=\3=\3>\3>\3>\3>\3>\7>\u01ea\n>\f>\16"+
		">\u01ed\13>\3?\3?\3?\3?\3@\3@\3@\3@\7@\u01f7\n@\f@\16@\u01fa\13@\3@\3"+
		"@\3\u00e8\2A\3\3\5\4\7\5\t\6\13\7\r\b\17\t\21\n\23\13\25\f\27\r\31\2\33"+
		"\2\35\2\37\16!\17#\20%\21\'\22)\23+\24-\25/\26\61\27\63\30\65\31\67\32"+
		"9\33;\34=\35?\36A\37C E!G\"I#K$M%O&Q\'S(U)W*Y+[,]-_.a/c\60e\61g\62i\63"+
		"k\64m\65o\66q\67s8u9w:y;{<}=\177>\3\2\t\3\2\62;\5\2\62;CHch\4\2C\\c|\4"+
		"\2/\60aa\4\2//aa\5\2\13\f\17\17\"\"\4\2\f\f\17\17\2\u0205\2\3\3\2\2\2"+
		"\2\5\3\2\2\2\2\7\3\2\2\2\2\t\3\2\2\2\2\13\3\2\2\2\2\r\3\2\2\2\2\17\3\2"+
		"\2\2\2\21\3\2\2\2\2\23\3\2\2\2\2\25\3\2\2\2\2\27\3\2\2\2\2\37\3\2\2\2"+
		"\2!\3\2\2\2\2#\3\2\2\2\2%\3\2\2\2\2\'\3\2\2\2\2)\3\2\2\2\2+\3\2\2\2\2"+
		"-\3\2\2\2\2/\3\2\2\2\2\61\3\2\2\2\2\63\3\2\2\2\2\65\3\2\2\2\2\67\3\2\2"+
		"\2\29\3\2\2\2\2;\3\2\2\2\2=\3\2\2\2\2?\3\2\2\2\2A\3\2\2\2\2C\3\2\2\2\2"+
		"E\3\2\2\2\2G\3\2\2\2\2I\3\2\2\2\2K\3\2\2\2\2M\3\2\2\2\2O\3\2\2\2\2Q\3"+
		"\2\2\2\2S\3\2\2\2\2U\3\2\2\2\2W\3\2\2\2\2Y\3\2\2\2\2[\3\2\2\2\2]\3\2\2"+
		"\2\2_\3\2\2\2\2a\3\2\2\2\2c\3\2\2\2\2e\3\2\2\2\2g\3\2\2\2\2i\3\2\2\2\2"+
		"k\3\2\2\2\2m\3\2\2\2\2o\3\2\2\2\2q\3\2\2\2\2s\3\2\2\2\2u\3\2\2\2\2w\3"+
		"\2\2\2\2y\3\2\2\2\2{\3\2\2\2\2}\3\2\2\2\2\177\3\2\2\2\3\u0081\3\2\2\2"+
		"\5\u0083\3\2\2\2\7\u0085\3\2\2\2\t\u0087\3\2\2\2\13\u0089\3\2\2\2\r\u008b"+
		"\3\2\2\2\17\u008e\3\2\2\2\21\u009e\3\2\2\2\23\u00a0\3\2\2\2\25\u00a2\3"+
		"\2\2\2\27\u00a4\3\2\2\2\31\u00a6\3\2\2\2\33\u00a8\3\2\2\2\35\u00aa\3\2"+
		"\2\2\37\u00ac\3\2\2\2!\u00b4\3\2\2\2#\u00b8\3\2\2\2%\u00bf\3\2\2\2\'\u00c6"+
		"\3\2\2\2)\u00ce\3\2\2\2+\u00d7\3\2\2\2-\u00e4\3\2\2\2/\u00ed\3\2\2\2\61"+
		"\u00f4\3\2\2\2\63\u00f7\3\2\2\2\65\u00fc\3\2\2\2\67\u00fe\3\2\2\29\u0101"+
		"\3\2\2\2;\u0106\3\2\2\2=\u0109\3\2\2\2?\u010f\3\2\2\2A\u011f\3\2\2\2C"+
		"\u0126\3\2\2\2E\u012b\3\2\2\2G\u0132\3\2\2\2I\u0139\3\2\2\2K\u0141\3\2"+
		"\2\2M\u0149\3\2\2\2O\u0152\3\2\2\2Q\u0159\3\2\2\2S\u0162\3\2\2\2U\u016a"+
		"\3\2\2\2W\u016e\3\2\2\2Y\u0174\3\2\2\2[\u0177\3\2\2\2]\u017f\3\2\2\2_"+
		"\u0185\3\2\2\2a\u018a\3\2\2\2c\u018e\3\2\2\2e\u0196\3\2\2\2g\u019a\3\2"+
		"\2\2i\u01a4\3\2\2\2k\u01ab\3\2\2\2m\u01b0\3\2\2\2o\u01ba\3\2\2\2q\u01c3"+
		"\3\2\2\2s\u01c9\3\2\2\2u\u01d4\3\2\2\2w\u01d9\3\2\2\2y\u01de\3\2\2\2{"+
		"\u01e4\3\2\2\2}\u01ee\3\2\2\2\177\u01f2\3\2\2\2\u0081\u0082\7?\2\2\u0082"+
		"\4\3\2\2\2\u0083\u0084\7=\2\2\u0084\6\3\2\2\2\u0085\u0086\7<\2\2\u0086"+
		"\b\3\2\2\2\u0087\u0088\7\60\2\2\u0088\n\3\2\2\2\u0089\u008a\7.\2\2\u008a"+
		"\f\3\2\2\2\u008b\u008c\7\60\2\2\u008c\u008d\7\60\2\2\u008d\16\3\2\2\2"+
		"\u008e\u008f\7z\2\2\u008f\u0090\7z\2\2\u0090\u0091\7z\2\2\u0091\u0092"+
		"\7z\2\2\u0092\u0093\7{\2\2\u0093\u0094\7{\2\2\u0094\u0095\7{\2\2\u0095"+
		"\u0096\7{\2\2\u0096\u0097\7{\2\2\u0097\u0098\7|\2\2\u0098\u0099\7|\2\2"+
		"\u0099\u009a\7|\2\2\u009a\u009b\7|\2\2\u009b\u009c\7|\2\2\u009c\u009d"+
		"\7|\2\2\u009d\20\3\2\2\2\u009e\u009f\7}\2\2\u009f\22\3\2\2\2\u00a0\u00a1"+
		"\7\177\2\2\u00a1\24\3\2\2\2\u00a2\u00a3\7*\2\2\u00a3\26\3\2\2\2\u00a4"+
		"\u00a5\7+\2\2\u00a5\30\3\2\2\2\u00a6\u00a7\t\2\2\2\u00a7\32\3\2\2\2\u00a8"+
		"\u00a9\t\3\2\2\u00a9\34\3\2\2\2\u00aa\u00ab\t\4\2\2\u00ab\36\3\2\2\2\u00ac"+
		"\u00ad\7\'\2\2\u00ad\u00af\5\33\16\2\u00ae\u00b0\5\33\16\2\u00af\u00ae"+
		"\3\2\2\2\u00b0\u00b1\3\2\2\2\u00b1\u00af\3\2\2\2\u00b1\u00b2\3\2\2\2\u00b2"+
		" \3\2\2\2\u00b3\u00b5\5\31\r\2\u00b4\u00b3\3\2\2\2\u00b5\u00b6\3\2\2\2"+
		"\u00b6\u00b4\3\2\2\2\u00b6\u00b7\3\2\2\2\u00b7\"\3\2\2\2\u00b8\u00b9\7"+
		"u\2\2\u00b9\u00ba\7q\2\2\u00ba\u00bb\7w\2\2\u00bb\u00bc\7t\2\2\u00bc\u00bd"+
		"\7e\2\2\u00bd\u00be\7g\2\2\u00be$\3\2\2\2\u00bf\u00c0\7v\2\2\u00c0\u00c1"+
		"\7c\2\2\u00c1\u00c2\7t\2\2\u00c2\u00c3\7i\2\2\u00c3\u00c4\7g\2\2\u00c4"+
		"\u00c5\7v\2\2\u00c5&\3\2\2\2\u00c6\u00c7\7s\2\2\u00c7\u00c8\7w\2\2\u00c8"+
		"\u00c9\7g\2\2\u00c9\u00ca\7t\2\2\u00ca\u00cb\7k\2\2\u00cb\u00cc\7g\2\2"+
		"\u00cc\u00cd\7f\2\2\u00cd(\3\2\2\2\u00ce\u00cf\7r\2\2\u00cf\u00d0\7t\2"+
		"\2\u00d0\u00d1\7q\2\2\u00d1\u00d2\7f\2\2\u00d2\u00d3\7w\2\2\u00d3\u00d4"+
		"\7e\2\2\u00d4\u00d5\7g\2\2\u00d5\u00d6\7f\2\2\u00d6*\3\2\2\2\u00d7\u00d8"+
		"\7$\2\2\u00d8\u00df\5\35\17\2\u00d9\u00de\5\35\17\2\u00da\u00de\5\31\r"+
		"\2\u00db\u00de\t\5\2\2\u00dc\u00de\5\33\16\2\u00dd\u00d9\3\2\2\2\u00dd"+
		"\u00da\3\2\2\2\u00dd\u00db\3\2\2\2\u00dd\u00dc\3\2\2\2\u00de\u00e1\3\2"+
		"\2\2\u00df\u00dd\3\2\2\2\u00df\u00e0\3\2\2\2\u00e0\u00e2\3\2\2\2\u00e1"+
		"\u00df\3\2\2\2\u00e2\u00e3\7$\2\2\u00e3,\3\2\2\2\u00e4\u00e8\7$\2\2\u00e5"+
		"\u00e7\13\2\2\2\u00e6\u00e5\3\2\2\2\u00e7\u00ea\3\2\2\2\u00e8\u00e9\3"+
		"\2\2\2\u00e8\u00e6\3\2\2\2\u00e9\u00eb\3\2\2\2\u00ea\u00e8\3\2\2\2\u00eb"+
		"\u00ec\7$\2\2\u00ec.\3\2\2\2\u00ed\u00ee\7c\2\2\u00ee\u00ef\7r\2\2\u00ef"+
		"\u00f0\7r\2\2\u00f0\u00f1\7g\2\2\u00f1\u00f2\7p\2\2\u00f2\u00f3\7f\2\2"+
		"\u00f3\60\3\2\2\2\u00f4\u00f5\7c\2\2\u00f5\u00f6\7u\2\2\u00f6\62\3\2\2"+
		"\2\u00f7\u00f8\7e\2\2\u00f8\u00f9\7c\2\2\u00f9\u00fa\7u\2\2\u00fa\u00fb"+
		"\7v\2\2\u00fb\64\3\2\2\2\u00fc\u00fd\7e\2\2\u00fd\66\3\2\2\2\u00fe\u00ff"+
		"\7e\2\2\u00ff\u0100\7e\2\2\u01008\3\2\2\2\u0101\u0102\7e\2\2\u0102\u0103"+
		"\7q\2\2\u0103\u0104\7f\2\2\u0104\u0105\7g\2\2\u0105:\3\2\2\2\u0106\u0107"+
		"\7e\2\2\u0107\u0108\7r\2\2\u0108<\3\2\2\2\u0109\u010a\7e\2\2\u010a\u010b"+
		"\7j\2\2\u010b\u010c\7g\2\2\u010c\u010d\7e\2\2\u010d\u010e\7m\2\2\u010e"+
		">\3\2\2\2\u010f\u0110\7e\2\2\u0110\u0111\7q\2\2\u0111\u0112\7f\2\2\u0112"+
		"\u0113\7g\2\2\u0113\u0114\7c\2\2\u0114\u0115\7d\2\2\u0115\u0116\7n\2\2"+
		"\u0116\u0117\7g\2\2\u0117\u0118\7E\2\2\u0118\u0119\7q\2\2\u0119\u011a"+
		"\7p\2\2\u011a\u011b\7e\2\2\u011b\u011c\7g\2\2\u011c\u011d\7r\2\2\u011d"+
		"\u011e\7v\2\2\u011e@\3\2\2\2\u011f\u0120\7e\2\2\u0120\u0121\7q\2\2\u0121"+
		"\u0122\7f\2\2\u0122\u0123\7k\2\2\u0123\u0124\7p\2\2\u0124\u0125\7i\2\2"+
		"\u0125B\3\2\2\2\u0126\u0127\7e\2\2\u0127\u0128\7q\2\2\u0128\u0129\7r\2"+
		"\2\u0129\u012a\7{\2\2\u012aD\3\2\2\2\u012b\u012c\7e\2\2\u012c\u012d\7"+
		"t\2\2\u012d\u012e\7g\2\2\u012e\u012f\7c\2\2\u012f\u0130\7v\2\2\u0130\u0131"+
		"\7g\2\2\u0131F\3\2\2\2\u0132\u0133\7f\2\2\u0133\u0134\7c\2\2\u0134\u0135"+
		"\7v\2\2\u0135\u0136\7g\2\2\u0136\u0137\7Q\2\2\u0137\u0138\7r\2\2\u0138"+
		"H\3\2\2\2\u0139\u013a\7f\2\2\u013a\u013b\7g\2\2\u013b\u013c\7h\2\2\u013c"+
		"\u013d\7c\2\2\u013d\u013e\7w\2\2\u013e\u013f\7n\2\2\u013f\u0140\7v\2\2"+
		"\u0140J\3\2\2\2\u0141\u0142\7f\2\2\u0142\u0143\7k\2\2\u0143\u0144\7u\2"+
		"\2\u0144\u0145\7r\2\2\u0145\u0146\7n\2\2\u0146\u0147\7c\2\2\u0147\u0148"+
		"\7{\2\2\u0148L\3\2\2\2\u0149\u014a\7g\2\2\u014a\u014b\7p\2\2\u014b\u014c"+
		"\7f\2\2\u014c\u014d\7i\2\2\u014d\u014e\7t\2\2\u014e\u014f\7q\2\2\u014f"+
		"\u0150\7w\2\2\u0150\u0151\7r\2\2\u0151N\3\2\2\2\u0152\u0153\7g\2\2\u0153"+
		"\u0154\7u\2\2\u0154\u0155\7e\2\2\u0155\u0156\7c\2\2\u0156\u0157\7r\2\2"+
		"\u0157\u0158\7g\2\2\u0158P\3\2\2\2\u0159\u015a\7g\2\2\u015a\u015b\7x\2"+
		"\2\u015b\u015c\7c\2\2\u015c\u015d\7n\2\2\u015d\u015e\7w\2\2\u015e\u015f"+
		"\7c\2\2\u015f\u0160\7v\2\2\u0160\u0161\7g\2\2\u0161R\3\2\2\2\u0162\u0163"+
		"\7g\2\2\u0163\u0164\7z\2\2\u0164\u0165\7v\2\2\u0165\u0166\7g\2\2\u0166"+
		"\u0167\7p\2\2\u0167\u0168\7f\2\2\u0168\u0169\7u\2\2\u0169T\3\2\2\2\u016a"+
		"\u016b\7h\2\2\u016b\u016c\7q\2\2\u016c\u016d\7t\2\2\u016dV\3\2\2\2\u016e"+
		"\u016f\7i\2\2\u016f\u0170\7t\2\2\u0170\u0171\7q\2\2\u0171\u0172\7w\2\2"+
		"\u0172\u0173\7r\2\2\u0173X\3\2\2\2\u0174\u0175\7k\2\2\u0175\u0176\7f\2"+
		"\2\u0176Z\3\2\2\2\u0177\u0178\7k\2\2\u0178\u0179\7o\2\2\u0179\u017a\7"+
		"r\2\2\u017a\u017b\7q\2\2\u017b\u017c\7t\2\2\u017c\u017d\7v\2\2\u017d\u017e"+
		"\7u\2\2\u017e\\\3\2\2\2\u017f\u0180\7k\2\2\u0180\u0181\7p\2\2\u0181\u0182"+
		"\7r\2\2\u0182\u0183\7w\2\2\u0183\u0184\7v\2\2\u0184^\3\2\2\2\u0185\u0186"+
		"\7o\2\2\u0186\u0187\7c\2\2\u0187\u0188\7m\2\2\u0188\u0189\7g\2\2\u0189"+
		"`\3\2\2\2\u018a\u018b\7o\2\2\u018b\u018c\7c\2\2\u018c\u018d\7r\2\2\u018d"+
		"b\3\2\2\2\u018e\u018f\7r\2\2\u018f\u0190\7q\2\2\u0190\u0191\7k\2\2\u0191"+
		"\u0192\7p\2\2\u0192\u0193\7v\2\2\u0193\u0194\7g\2\2\u0194\u0195\7t\2\2"+
		"\u0195d\3\2\2\2\u0196\u0197\7s\2\2\u0197\u0198\7v\2\2\u0198\u0199\7{\2"+
		"\2\u0199f\3\2\2\2\u019a\u019b\7t\2\2\u019b\u019c\7g\2\2\u019c\u019d\7"+
		"h\2\2\u019d\u019e\7g\2\2\u019e\u019f\7t\2\2\u019f\u01a0\7g\2\2\u01a0\u01a1"+
		"\7p\2\2\u01a1\u01a2\7e\2\2\u01a2\u01a3\7g\2\2\u01a3h\3\2\2\2\u01a4\u01a5"+
		"\7u\2\2\u01a5\u01a6\7{\2\2\u01a6\u01a7\7u\2\2\u01a7\u01a8\7v\2\2\u01a8"+
		"\u01a9\7g\2\2\u01a9\u01aa\7o\2\2\u01aaj\3\2\2\2\u01ab\u01ac\7v\2\2\u01ac"+
		"\u01ad\7j\2\2\u01ad\u01ae\7g\2\2\u01ae\u01af\7p\2\2\u01afl\3\2\2\2\u01b0"+
		"\u01b1\7v\2\2\u01b1\u01b2\7t\2\2\u01b2\u01b3\7c\2\2\u01b3\u01b4\7p\2\2"+
		"\u01b4\u01b5\7u\2\2\u01b5\u01b6\7n\2\2\u01b6\u01b7\7c\2\2\u01b7\u01b8"+
		"\7v\2\2\u01b8\u01b9\7g\2\2\u01b9n\3\2\2\2\u01ba\u01bb\7v\2\2\u01bb\u01bc"+
		"\7t\2\2\u01bc\u01bd\7w\2\2\u01bd\u01be\7p\2\2\u01be\u01bf\7e\2\2\u01bf"+
		"\u01c0\7c\2\2\u01c0\u01c1\7v\2\2\u01c1\u01c2\7g\2\2\u01c2p\3\2\2\2\u01c3"+
		"\u01c4\7v\2\2\u01c4\u01c5\7{\2\2\u01c5\u01c6\7r\2\2\u01c6\u01c7\7g\2\2"+
		"\u01c7\u01c8\7u\2\2\u01c8r\3\2\2\2\u01c9\u01ca\7v\2\2\u01ca\u01cb\7{\2"+
		"\2\u01cb\u01cc\7r\2\2\u01cc\u01cd\7g\2\2\u01cd\u01ce\7-\2\2\u01ce\u01cf"+
		"\7v\2\2\u01cf\u01d0\7{\2\2\u01d0\u01d1\7r\2\2\u01d1\u01d2\7g\2\2\u01d2"+
		"\u01d3\7u\2\2\u01d3t\3\2\2\2\u01d4\u01d5\7w\2\2\u01d5\u01d6\7w\2\2\u01d6"+
		"\u01d7\7k\2\2\u01d7\u01d8\7f\2\2\u01d8v\3\2\2\2\u01d9\u01da\7w\2\2\u01da"+
		"\u01db\7u\2\2\u01db\u01dc\7g\2\2\u01dc\u01dd\7u\2\2\u01ddx\3\2\2\2\u01de"+
		"\u01df\7y\2\2\u01df\u01e0\7j\2\2\u01e0\u01e1\7g\2\2\u01e1\u01e2\7t\2\2"+
		"\u01e2\u01e3\7g\2\2\u01e3z\3\2\2\2\u01e4\u01eb\5\35\17\2\u01e5\u01ea\5"+
		"\35\17\2\u01e6\u01ea\5\31\r\2\u01e7\u01ea\t\6\2\2\u01e8\u01ea\5\33\16"+
		"\2\u01e9\u01e5\3\2\2\2\u01e9\u01e6\3\2\2\2\u01e9\u01e7\3\2\2\2\u01e9\u01e8"+
		"\3\2\2\2\u01ea\u01ed\3\2\2\2\u01eb\u01e9\3\2\2\2\u01eb\u01ec\3\2\2\2\u01ec"+
		"|\3\2\2\2\u01ed\u01eb\3\2\2\2\u01ee\u01ef\t\7\2\2\u01ef\u01f0\3\2\2\2"+
		"\u01f0\u01f1\b?\2\2\u01f1~\3\2\2\2\u01f2\u01f3\7\61\2\2\u01f3\u01f4\7"+
		"\61\2\2\u01f4\u01f8\3\2\2\2\u01f5\u01f7\n\b\2\2\u01f6\u01f5\3\2\2\2\u01f7"+
		"\u01fa\3\2\2\2\u01f8\u01f6\3\2\2\2\u01f8\u01f9\3\2\2\2\u01f9\u01fb\3\2"+
		"\2\2\u01fa\u01f8\3\2\2\2\u01fb\u01fc\b@\2\2\u01fc\u0080\3\2\2\2\13\2\u00b1"+
		"\u00b6\u00dd\u00df\u00e8\u01e9\u01eb\u01f8\3\b\2\2";
	public static final ATN _ATN =
		new ATNDeserializer().deserialize(_serializedATN.toCharArray());
	static {
		_decisionToDFA = new DFA[_ATN.getNumberOfDecisions()];
		for (int i = 0; i < _ATN.getNumberOfDecisions(); i++) {
			_decisionToDFA[i] = new DFA(_ATN.getDecisionState(i), i);
		}
	}
}
