name: Reviewer Check
on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Add Migration Reviewers if Necessary
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if migrations changed
        id: migrations-changed
        uses: tj-actions/changed-files@v35
        with:
          files: |
            hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java
      - name: Add migration reviewers if migration files changed
        if: steps.migrations-changed.outputs.any_changed == 'true'
        uses: madrapps/add-reviewers@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: michaelabuckley,jamesagnew
